# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information on how to use this file.

app = "matwork"
primary_region = "iad"
console_command = "/app/bin/matwork remote"

[build]

[env]
  PHX_HOST = "matwork.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "/app/bin/migrate"
