defmodule Matwork.Repo.Migrations.CreateWebhookEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:webhook_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :external_id, :text, null: false
      add :payload, :map, null: false
      add :processed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:webhook_events, [:provider, :external_id],
             name: "webhook_events_unique_provider_event_index"
           )
  end

  def down do
    drop_if_exists unique_index(:webhook_events, [:provider, :external_id],
                     name: "webhook_events_unique_provider_event_index"
                   )

    drop table(:webhook_events)
  end
end
