defmodule Matwork.Repo.Migrations.AddMembership do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "memberships_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:memberships, [:gym_id, :user_id],
             name: "memberships_unique_user_per_gym_index"
           )
  end

  def down do
    drop constraint(:memberships, "memberships_gym_id_fkey")

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop_if_exists unique_index(:memberships, [:gym_id, :user_id],
                     name: "memberships_unique_user_per_gym_index"
                   )

    drop table(:memberships)
  end
end
