defmodule Matwork.Repo.Migrations.AddInvite do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:invites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :role, :text, null: false
      add :token, :text, null: false
      add :accepted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "invites_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:invites, [:gym_id, :token], name: "invites_unique_token_index")
  end

  def down do
    drop constraint(:invites, "invites_gym_id_fkey")

    drop_if_exists unique_index(:invites, [:gym_id, :token], name: "invites_unique_token_index")

    drop table(:invites)
  end
end
