defmodule Matwork.Repo.Migrations.AddGymsDomainAndGym do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:gyms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :citext, null: false
      add :custom_domain, :citext
      add :stripe_account_id, :text
      add :stripe_onboarding_state, :text, null: false, default: "none"
      add :application_fee_percent, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "gyms_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:gyms, [:custom_domain], name: "gyms_unique_custom_domain_index")

    create unique_index(:gyms, [:slug], name: "gyms_unique_slug_index")
  end

  def down do
    drop constraint(:gyms, "gyms_owner_id_fkey")

    drop_if_exists unique_index(:gyms, [:slug], name: "gyms_unique_slug_index")

    drop_if_exists unique_index(:gyms, [:custom_domain], name: "gyms_unique_custom_domain_index")

    drop table(:gyms)
  end
end
