defmodule Matwork.Repo.Migrations.CreateCourseSections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:course_sections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "course_sections_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :course_id,
          references(:courses,
            column: :id,
            name: "course_sections_course_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:course_sections, "course_sections_gym_id_fkey")

    drop constraint(:course_sections, "course_sections_course_id_fkey")

    drop table(:course_sections)
  end
end
