defmodule Matwork.Repo.Migrations.DropRedundantGymIdIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:lessons, [:gym_id])

    drop_if_exists index(:course_sections, [:gym_id])
  end

  def down do
    create index(:course_sections, [:gym_id])

    create index(:lessons, [:gym_id])
  end
end
