defmodule Matwork.Repo.Migrations.AddLessonVideo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lessons) do
      add :video_id,
          references(:videos,
            column: :id,
            name: "lessons_video_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:lessons, "lessons_video_id_fkey")

    alter table(:lessons) do
      remove :video_id
    end
  end
end
