defmodule Matwork.Repo.Migrations.CreateVideos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:videos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :mux_upload_id, :text, null: false
      add :mux_asset_id, :text
      add :mux_playback_id, :text
      add :status, :text, null: false, default: "pending_upload"
      add :duration_seconds, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "videos_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :uploaded_by_id,
          references(:users,
            column: :id,
            name: "videos_uploaded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:videos, [:gym_id, :mux_upload_id])

    create index(:videos, [:gym_id])
  end

  def down do
    drop constraint(:videos, "videos_gym_id_fkey")

    drop constraint(:videos, "videos_uploaded_by_id_fkey")

    drop_if_exists index(:videos, [:gym_id])

    drop_if_exists index(:videos, [:gym_id, :mux_upload_id])

    drop table(:videos)
  end
end
