defmodule Matwork.Repo.Migrations.CreateLessons do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lessons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :free_preview, :boolean, null: false, default: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :gym_id,
          references(:gyms,
            column: :id,
            name: "lessons_gym_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :section_id,
          references(:course_sections,
            column: :id,
            name: "lessons_section_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:lessons, "lessons_gym_id_fkey")

    drop constraint(:lessons, "lessons_section_id_fkey")

    drop table(:lessons)
  end
end
